(ns adversarial-sketch.config)
(def guidance-token-size 24)
(def reserved-token-size 7)
(def extra-size-image-embed 50)
(def embed-size (+ guidance-token-size extra-size-image-embed reserved-token-size))
(def lstm-size 25)
(def dropout 0.75)
(def num-data 100)
(def batch-size 1)
(def num-iters 1)
(def learning-rate 1)
(def max_seq_length 100)
